name: goat
version: '0.1'
summary: Goat database management
description: |
  Goat database management, DB frontend written in Qt5

grade: devel
confinement: devmode

architectures: [amd64]
base: core18

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
  goat:
    # See 'snapcraft plugins'
    plugin: qmake
    source: https://github.com/mispp/goat.git
    after: [desktop-qt5]
    qt-version: qt5
    build-packages:
      - build-essential
      - g++
      - qtbase5-dev
      - qt5-qmake
      - qtscript5-dev
      - qttools5-dev-tools
      - pkg-config
    stage-packages:
      - libqt5sql5-psql
      - libqt5sql5-mysql
      - libqt5sql5-odbc
      - libqt5widgets5
      - libqt5concurrent5
      - libqt5core5a
      - libqt5gui5
      - libqt5sql5
      - libqt5dbus5
      - postgresql-client
      - mysql-client
      - qtwayland5

apps:
  goat:
    command: desktop-launch $SNAP/usr/bin/goat   
    plugs: [home, desktop, desktop-legacy, x11, network, wayland]

